title: Your awesome title
author: GitHub User
email: viliam.dzurban@gmail.com
description: > # THIS IS DESCRIPTION

# social links
twitter_username: don't have twitter yet
github_username:  LOLIMHUMAN

show_excerpts: true # set to false to remove excerpts on the homepage
